// module.exports =  { /* common epxort js  not es6 epxort*/
  export default   { /* this is es6 epxort*/
    products: [
      {
        _id: '111111111111111111111111',
        name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
        category: 'Shirts',
        image: '/images/product-1.jpeg',
        price: 59,
        brand: 'Hiskywin',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '222222222222222222222222',
        name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
        category: 'Shirts',
        image: '/images/product-2.jpeg',
        price: 70,
        brand: 'Nike',
        rating: 5,
        numReviews: 51,
      },
      {
        _id: '3',
        name: 'Adidas Mens Long Sleeve Hoodie',
        category: 'Shirts',
        image: '/images/product-3.jpeg',
        price: 59,
        brand: 'Adidas',
        rating: 4,
        numReviews: 45,
      },
      {
        _id: '4',
        name: 'Under Armour Mens Sportstyle Tricot Joggers',
        category: 'Pants',
        image: '/images/product-4.jpeg',
        price: 90,
        brand: 'Under Armour',
        rating: 2.5,
        numReviews: 198,
        countInStock: 6,
      },
      {
        _id: '5',
        name: 'Champion Mens Graphic Powerblend Fleece Jogger',
        category: 'Pants',
        image: '/images/product-5.jpeg',
        price: 119,
        brand: 'Champion',
        rating: 3.5,
        numReviews: 89,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
        category: 'Pants',
        image: '/images/product-6.jpeg',
        price: 85,
        brand: 'Aelfric Eden',
        rating: 4.5,
        numReviews: 45,
        countInStock: 6,
      },
    ],
  };
